DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS post_category;

DROP TABLE IF EXISTS post_reactions;

DROP TABLE IF EXISTS comment_reactions;

DROP TABLE IF EXISTS images;
